name: Download and Push Files

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Run daily at UTC midnight

jobs:
  download_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout city-of-toronto-contracts-data
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_CITYOFTORONTOCONTRACTSDATA }}
          repository: 'RamVasuthevan/city-of-toronto-contracts-data'
          path: city-of-toronto-contracts-data
          ref: 'main'

      - name: Download Competitive Contracts File
        run: |
          curl -o city-of-toronto-contracts-data/competitive-contracts.xml -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36" https://wx.toronto.ca/inter/pmmd/callawards.nsf/postedawards?ReadViewEntries

      - name: Download Non-Competitive Contracts File
        run: |
          curl -o city-of-toronto-contracts-data/non-competitive-contracts.xml -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36" https://wx.toronto.ca/inter/pmmd/solesource.nsf/posted?ReadViewEntries

      - name: Download Solicitations File 
        run: |
          curl -o city-of-toronto-contracts-data/solicitations.xml -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36" https://wx.toronto.ca/inter/pmmd/calls.nsf/002FC5CABA39CB078525783300553575?readviewentries

      - name: Commit and Push if Files Changed
        run: |
          cd city-of-toronto-contracts-data
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add competitive-contracts.xml non-competitive-contracts.xml solicitations.xml
          timestamp=$(date -u)
          git commit -m "Downloaded: ${timestamp}: commit: ${{github.sha}}" || exit 0
          # Use force push to push changes
          git push --force
